// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentAPI.Data;

#nullable disable

namespace StudentAPI.Migrations
{
    [DbContext(typeof(StudentAPIDbContext))]
    [Migration("20231123084305_Updated Nac prop")]
    partial class UpdatedNacprop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentAPI.Domain.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("237b0357-dfb0-49e9-90a9-0a25933c439e"),
                            Name = "Introduction to programming"
                        },
                        new
                        {
                            Id = new Guid("5c47bab3-293b-4b64-8860-bdeb1516ed43"),
                            Name = "Web Programming and Implementation"
                        },
                        new
                        {
                            Id = new Guid("69e61e7e-6b80-4cde-b016-3a253e9a0c45"),
                            Name = "Java Programming"
                        },
                        new
                        {
                            Id = new Guid("0d06acb7-5ad4-458c-b26e-a3b390994335"),
                            Name = "Object Oriented Programming"
                        },
                        new
                        {
                            Id = new Guid("0d06acb7-5ad4-458c-b26e-a3b390994447"),
                            Name = "Calculus"
                        },
                        new
                        {
                            Id = new Guid("0d06acb7-5ad4-458c-b26e-a3b390995678"),
                            Name = "Data Structure and Algorythm"
                        });
                });

            modelBuilder.Entity("StudentAPI.Domain.Models.Ranking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rankings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9de3c6d-55e8-4857-9e8e-87a8c35f5ae0"),
                            Name = "Brilliant"
                        },
                        new
                        {
                            Id = new Guid("df1228e3-b8e6-4bd5-95a3-5b54e19b3a88"),
                            Name = "Average"
                        },
                        new
                        {
                            Id = new Guid("044677d4-ec73-4c97-a007-86530e9c0769"),
                            Name = "Needs more work"
                        });
                });

            modelBuilder.Entity("StudentAPI.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<Guid?>("RankingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RankingId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentAPI.Domain.Models.Student", b =>
                {
                    b.HasOne("StudentAPI.Domain.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("StudentAPI.Domain.Models.Ranking", "Ranking")
                        .WithMany()
                        .HasForeignKey("RankingId");

                    b.Navigation("Class");

                    b.Navigation("Ranking");
                });
#pragma warning restore 612, 618
        }
    }
}
